# Generated by Django 4.0.1 on 2023-09-16 20:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="El número debe estar en este formato.:                         '+593 999999999'.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefono')),
                ('nombre_completo', models.CharField(max_length=255, verbose_name='Nombres Completos')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('hora_inicio', models.TimeField(blank=True, null=True, verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(blank=True, null=True, verbose_name='Hora de Finalización')),
                ('carrera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservas.carreras', verbose_name='Carrera')),
                ('laboratorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservas.laboratorios', verbose_name='Laboratorio')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_cliente', models.CharField(choices=[('1', '07:30 a 08:30'), ('2', '08:30 a 09:30'), ('3', '09:30 a 10:30'), ('4', '10:30 a 11:30'), ('5', '11:30 a 12:30'), ('6', '13:30 a 14:30'), ('7', '14:30 a 15:30'), ('8', '15:30 a 16:30'), ('9', '16:30 a 17:30')], default='1', max_length=2, verbose_name='Horario seleccionado por el cliente')),
                ('agenda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consulta', to='reservas.agenda')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consulta', to='clientes.cliente')),
            ],
            options={
                'unique_together': {('agenda', 'cliente')},
            },
        ),
    ]
