# Generated by Django 4.0.1 on 2023-09-16 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_laboratorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='horario_cliente',
            field=models.CharField(choices=[('1', '07:30 a 08:30'), ('2', '08:30 a 09:30'), ('3', '09:30 a 10:30'), ('4', '10:30 a 11:30'), ('5', '11:30 a 12:30'), ('6', '13:30 a 14:30'), ('7', '14:30 a 15:30'), ('8', '15:30 a 16:30'), ('9', '16:30 a 17:30')], max_length=2, null=True, verbose_name='Horario seleccionado por el cliente'),
        ),
    ]
