# Generated by Django 4.0.1 on 2023-09-16 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
        ('clientes', '0003_consulta_horario_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_carrera', to='reservas.laboratorios', verbose_name='Carrera'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='laboratorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_laboratorio', to='reservas.laboratorios', verbose_name='Laboratorio'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='horario_cliente',
            field=models.CharField(choices=[('1', '07:30 a 08:30'), ('2', '08:30 a 09:30'), ('3', '09:30 a 10:30'), ('4', '10:30 a 11:30'), ('5', '11:30 a 12:30'), ('6', '13:30 a 14:30'), ('7', '14:30 a 15:30'), ('8', '15:30 a 16:30'), ('9', '16:30 a 17:30')], default='1', max_length=2, verbose_name='Horario seleccionado por el cliente'),
        ),
    ]
