# Generated by Django 4.0.1 on 2023-09-16 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
        ('clientes', '0004_alter_cliente_carrera_alter_cliente_laboratorio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='laboratorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservas.laboratorios', verbose_name='Laboratorio'),
        ),
    ]
