# Generated by Django 4.0.1 on 2023-09-16 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
        ('clientes', '0005_alter_cliente_laboratorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservas.carreras', verbose_name='Carrera'),
        ),
    ]
