# Generated by Django 4.0.1 on 2023-09-16 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laboratorios',
            old_name='carrera',
            new_name='carreras',
        ),
    ]
